version: '3.1'

services:
  node:
    build: .
    container_name: 'vk-bots-node'
    depends_on:
      - postgres
    ports:
      - "${PORT}:3000"
    environment:
      NODE_ENV: "${NODE_ENV}"
  postgres:
    container_name: 'vk-bots-postgres'
    image: postgres:14.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"