version: '3.1'

services:
  node:
    build: .
    container_name: 'vk-bots-node'
    depends_on:
      - postgres
    ports:
      - "${PORT}:3000"
    environment:
      NODE_ENV: "${NODE_ENV}"
    profiles: ["heroku"]
  postgres:
    container_name: 'vk-bots-postgres'
    image: postgres:14.2
    restart: always
    ports:
      - "${PGPORT}:5432"
    environment:
      POSTGRES_HOST: "${PGHOST}"
      POSTGRES_DB: "${PGDATABASE}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_USERNAME: "${PGUSER}"